name: animated_dragdrop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flextras: ^1.0.0
  intersperse: ^2.0.0
  collection: ^1.18.0
  dimensions_theme: ^0.1.1
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/adam_barth.jpg
    - assets/eric_seidel.jpg
    - assets/filip_hracek.jpg
    - assets/ian_hickson.png
